[package]
name = "map-generation"
version = "0.1.0"
edition = "2021"
[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.93"
common = { version = "0.1.0", path = "../common" }
cosmwasm-std.workspace = true
noise = { version = "0.8.0", features = ["images"] }
serde_json = "1.0.133"
