[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
abstract-adapter.workspace = true
abstract-client = { workspace = true, features = ["interchain"] }
abstract-interface = { workspace = true, features = ["interchain", "testing"] }
anyhow.workspace = true
common = { version = "0.1.0", path = "../common" }
cosmwasm-std.workspace = true
cw-orch.workspace = true
cw-orch-interchain = "0.8.1"
cw721.workspace = true
game-handler = { workspace = true }
nft = { workspace = true }
xion-adventures-hub = { workspace = true }
scripts = { workspace = true }
