/**
* This file was automatically generated by @abstract-money/ts-codegen@0.37.0-beta-5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

export type AccountTrace = "local" | {
  remote: TruncatedChainId[];
};
export type TruncatedChainId = string;
export type Uint128 = string;
export interface InstantiateMsg {
  admin_account: AccountId;
  metadata_base: FixedMetadata;
  mint_cost: Coin;
  mint_limit: number;
  token_uri_base: string;
}
export interface AccountId {
  seq: number;
  trace: AccountTrace;
}
export interface FixedMetadata {}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export type ExecuteMsg = {
  create_account: {
    city_map_index?: number | null;
    receiver?: AccountId | null;
  };
} | {
  move_player: {
    positions: Vec2[];
    token_id: string;
  };
};
export interface Vec2 {
  x: number;
  y: number;
}
export type QueryMsg = {
  config: {};
};
export interface MigrateMsg {}
export interface ConfigResponse {
  admin_account: AccountId;
  metadata_base: FixedMetadata;
  mint_cost: Coin;
  mint_limit: number;
  token_uri_base: string;
}