// @ts-nocheck
          /**
* This file was automatically generated by @abstract-money/ts-codegen@0.37.0-beta-3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

import { AccountTrace, TruncatedChainId, Uint128, InstantiateMsg, AccountId, FixedMetadata, Coin, ExecuteMsg, Vec2, QueryMsg, MigrateMsg, ConfigResponse } from "./GameHandler.types";
import { CamelCasedProperties } from "type-fest";
export abstract class GameHandlerExecuteMsgBuilder {
static createAccount = ({
  cityMapIndex,
  receiver
}: CamelCasedProperties<Extract<ExecuteMsg, {
  create_account: unknown;
}>["create_account"]>): ExecuteMsg => {
  return {
    create_account: ({
      city_map_index: cityMapIndex,
      receiver
    } as const)
  };
};
static movePlayer = ({
  positions,
  tokenId
}: CamelCasedProperties<Extract<ExecuteMsg, {
  move_player: unknown;
}>["move_player"]>): ExecuteMsg => {
  return {
    move_player: ({
      positions,
      token_id: tokenId
    } as const)
  };
};
}
export abstract class GameHandlerQueryMsgBuilder {
static config = (): QueryMsg => {
  return {
    config: ({} as const)
  };
};
}